//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTitle
    {
        public int titleSK { get; set; }
        public Nullable<int> pizzaFK { get; set; }
        public Nullable<int> orderFK { get; set; }
        public string pizzaName { get; set; }
        public int price { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PizzaList PizzaList { get; set; }
    }
}
